//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.ItsMe1110.ObjectBlogService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBlog", Namespace="http://schemas.datacontract.org/2004/07/VL.Blog.Objects.Entities")]
    [System.SerializableAttribute()]
    public partial class TBlog : VL.ItsMe1110.ObjectBlogService.IPDMTBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BlogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BreviaryContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastEditTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BlogId {
            get {
                return this.BlogIdField;
            }
            set {
                if ((this.BlogIdField.Equals(value) != true)) {
                    this.BlogIdField = value;
                    this.RaisePropertyChanged("BlogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BreviaryContent {
            get {
                return this.BreviaryContentField;
            }
            set {
                if ((object.ReferenceEquals(this.BreviaryContentField, value) != true)) {
                    this.BreviaryContentField = value;
                    this.RaisePropertyChanged("BreviaryContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedTime {
            get {
                return this.CreatedTimeField;
            }
            set {
                if ((this.CreatedTimeField.Equals(value) != true)) {
                    this.CreatedTimeField = value;
                    this.RaisePropertyChanged("CreatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastEditTime {
            get {
                return this.LastEditTimeField;
            }
            set {
                if ((this.LastEditTimeField.Equals(value) != true)) {
                    this.LastEditTimeField = value;
                    this.RaisePropertyChanged("LastEditTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IPDMTBase", Namespace="http://schemas.datacontract.org/2004/07/VL.Common.ORM")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VL.ItsMe1110.ObjectBlogService.TBlogDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VL.ItsMe1110.ObjectBlogService.TBlog))]
    public partial class IPDMTBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBlogDetail", Namespace="http://schemas.datacontract.org/2004/07/VL.Blog.Objects.Entities")]
    [System.SerializableAttribute()]
    public partial class TBlogDetail : VL.ItsMe1110.ObjectBlogService.IPDMTBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BlogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BlogId {
            get {
                return this.BlogIdField;
            }
            set {
                if ((this.BlogIdField.Equals(value) != true)) {
                    this.BlogIdField = value;
                    this.RaisePropertyChanged("BlogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObjectBlogService.IObjectBlogService")]
    public interface IObjectBlogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckAlive", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckAliveResponse")]
        bool CheckAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckAlive", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckAliveResponse")]
        System.Threading.Tasks.Task<bool> CheckAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckNodeReferences", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckNodeReferencesResponse")]
        VL.Common.Constraints.Protocol.DependencyResult CheckNodeReferences();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckNodeReferences", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckNodeReferencesResponse")]
        System.Threading.Tasks.Task<VL.Common.Constraints.Protocol.DependencyResult> CheckNodeReferencesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetAllBlogs", ReplyAction="http://tempuri.org/IObjectBlogService/GetAllBlogsResponse")]
        System.Collections.Generic.List<VL.ItsMe1110.ObjectBlogService.TBlog> GetAllBlogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetAllBlogs", ReplyAction="http://tempuri.org/IObjectBlogService/GetAllBlogsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<VL.ItsMe1110.ObjectBlogService.TBlog>> GetAllBlogsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetBlogDetail", ReplyAction="http://tempuri.org/IObjectBlogService/GetBlogDetailResponse")]
        VL.ItsMe1110.ObjectBlogService.TBlogDetail GetBlogDetail(System.Guid blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetBlogDetail", ReplyAction="http://tempuri.org/IObjectBlogService/GetBlogDetailResponse")]
        System.Threading.Tasks.Task<VL.ItsMe1110.ObjectBlogService.TBlogDetail> GetBlogDetailAsync(System.Guid blogId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObjectBlogServiceChannel : VL.ItsMe1110.ObjectBlogService.IObjectBlogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectBlogServiceClient : System.ServiceModel.ClientBase<VL.ItsMe1110.ObjectBlogService.IObjectBlogService>, VL.ItsMe1110.ObjectBlogService.IObjectBlogService {
        
        public ObjectBlogServiceClient() {
        }
        
        public ObjectBlogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjectBlogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectBlogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectBlogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckAlive() {
            return base.Channel.CheckAlive();
        }
        
        public System.Threading.Tasks.Task<bool> CheckAliveAsync() {
            return base.Channel.CheckAliveAsync();
        }
        
        public VL.Common.Constraints.Protocol.DependencyResult CheckNodeReferences() {
            return base.Channel.CheckNodeReferences();
        }
        
        public System.Threading.Tasks.Task<VL.Common.Constraints.Protocol.DependencyResult> CheckNodeReferencesAsync() {
            return base.Channel.CheckNodeReferencesAsync();
        }
        
        public System.Collections.Generic.List<VL.ItsMe1110.ObjectBlogService.TBlog> GetAllBlogs() {
            return base.Channel.GetAllBlogs();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<VL.ItsMe1110.ObjectBlogService.TBlog>> GetAllBlogsAsync() {
            return base.Channel.GetAllBlogsAsync();
        }
        
        public VL.ItsMe1110.ObjectBlogService.TBlogDetail GetBlogDetail(System.Guid blogId) {
            return base.Channel.GetBlogDetail(blogId);
        }
        
        public System.Threading.Tasks.Task<VL.ItsMe1110.ObjectBlogService.TBlogDetail> GetBlogDetailAsync(System.Guid blogId) {
            return base.Channel.GetBlogDetailAsync(blogId);
        }
    }
}
