//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VL.ItsMe1110.ObjectBlogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObjectBlogService.IObjectBlogService")]
    public interface IObjectBlogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckAlive", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckAliveResponse")]
        bool CheckAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckAlive", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckAliveResponse")]
        System.Threading.Tasks.Task<bool> CheckAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckNodeReferences", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckNodeReferencesResponse")]
        VL.Common.Object.Protocol.DependencyResult CheckNodeReferences();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFServiceNode/CheckNodeReferences", ReplyAction="http://tempuri.org/IWCFServiceNode/CheckNodeReferencesResponse")]
        System.Threading.Tasks.Task<VL.Common.Object.Protocol.DependencyResult> CheckNodeReferencesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetAllBlogs", ReplyAction="http://tempuri.org/IObjectBlogService/GetAllBlogsResponse")]
        VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>> GetAllBlogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetAllBlogs", ReplyAction="http://tempuri.org/IObjectBlogService/GetAllBlogsResponse")]
        System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>>> GetAllBlogsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetBlogBody", ReplyAction="http://tempuri.org/IObjectBlogService/GetBlogBodyResponse")]
        VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlog> GetBlogBody(System.Guid blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetBlogBody", ReplyAction="http://tempuri.org/IObjectBlogService/GetBlogBodyResponse")]
        System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlog>> GetBlogBodyAsync(System.Guid blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetBlogDetail", ReplyAction="http://tempuri.org/IObjectBlogService/GetBlogDetailResponse")]
        VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlogDetail> GetBlogDetail(System.Guid blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetBlogDetail", ReplyAction="http://tempuri.org/IObjectBlogService/GetBlogDetailResponse")]
        System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlogDetail>> GetBlogDetailAsync(System.Guid blogId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetVisibleBlogs", ReplyAction="http://tempuri.org/IObjectBlogService/GetVisibleBlogsResponse")]
        VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>> GetVisibleBlogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjectBlogService/GetVisibleBlogs", ReplyAction="http://tempuri.org/IObjectBlogService/GetVisibleBlogsResponse")]
        System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>>> GetVisibleBlogsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObjectBlogServiceChannel : VL.ItsMe1110.ObjectBlogService.IObjectBlogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjectBlogServiceClient : System.ServiceModel.ClientBase<VL.ItsMe1110.ObjectBlogService.IObjectBlogService>, VL.ItsMe1110.ObjectBlogService.IObjectBlogService {
        
        public ObjectBlogServiceClient() {
        }
        
        public ObjectBlogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjectBlogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectBlogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjectBlogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckAlive() {
            return base.Channel.CheckAlive();
        }
        
        public System.Threading.Tasks.Task<bool> CheckAliveAsync() {
            return base.Channel.CheckAliveAsync();
        }
        
        public VL.Common.Object.Protocol.DependencyResult CheckNodeReferences() {
            return base.Channel.CheckNodeReferences();
        }
        
        public System.Threading.Tasks.Task<VL.Common.Object.Protocol.DependencyResult> CheckNodeReferencesAsync() {
            return base.Channel.CheckNodeReferencesAsync();
        }
        
        public VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>> GetAllBlogs() {
            return base.Channel.GetAllBlogs();
        }
        
        public System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>>> GetAllBlogsAsync() {
            return base.Channel.GetAllBlogsAsync();
        }
        
        public VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlog> GetBlogBody(System.Guid blogId) {
            return base.Channel.GetBlogBody(blogId);
        }
        
        public System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlog>> GetBlogBodyAsync(System.Guid blogId) {
            return base.Channel.GetBlogBodyAsync(blogId);
        }
        
        public VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlogDetail> GetBlogDetail(System.Guid blogId) {
            return base.Channel.GetBlogDetail(blogId);
        }
        
        public System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<VL.Common.Object.VL.Blog.TBlogDetail>> GetBlogDetailAsync(System.Guid blogId) {
            return base.Channel.GetBlogDetailAsync(blogId);
        }
        
        public VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>> GetVisibleBlogs() {
            return base.Channel.GetVisibleBlogs();
        }
        
        public System.Threading.Tasks.Task<VL.Common.Object.Protocol.Report<System.Collections.Generic.List<VL.Common.Object.VL.Blog.TBlog>>> GetVisibleBlogsAsync() {
            return base.Channel.GetVisibleBlogsAsync();
        }
    }
}
